### ISSUE TITLE
What exactly are the license use terms?

### ISSUE THREAD

**Issue by Metallicow** [arvida/emoji-cheat-sheet.com#352]
What exactly are the license use terms for using these?
For example are they CC0, public domain, etc...
Can they for example all be embedded in a python file can compiled into a project or as loose files.
The LICENSE file only shows copyrights but no actual real "terms of use" blerbs for the general public.
Just because a directory is labeled public doesn't always mean the context of "freely available for any use"...
Could you clear this up please(in the license file).

**Comment by cyberfox** [comment]
All of the actual images are All Rights Reserved; so as far as I can tell...no, we can't use them.  It's a semi-useful reference, but without permission to use the actual images, anybody using this is living under persistent threat of copyright infringement from, mainly, Apple.

It'd be a lot more helpful if there was a translation between the short text and the Unicode entries, even though they're not necessarily as well supported, because then at least it could be left up to the browser to support it.

*Using* one of the services that support the short-texts, this is a really useful list.  *Building* a service that wants to show emoji...less so. :disappointed:

**Comment by yincrash** [comment]
If you want to avoid the specter of infringement, you can always switch out the apple emoji set with google's emojis which fall under AOSP's license which is Apache 2. Something like https://github.com/iamcal/emoji-data has all the google emoji images extracted and is itself covered with the MIT license.

**Comment by Metallicow** [comment]
I find it enlightening and free but also a sickining thought on open source/repositories...
I guess many have crossed the thought that almost **anything** can be automated nowadays.
Some would write their own software that reads and writes out ""code"" and "allow" others to license it as free any free creation(input &/or output) duly noted.
This is the media's fault, not always the people that run it.
My software has the abilities to create something useful that others have used to destroy civilizations entirely with. Embroidery/textiles
I abstain from this conversation. Thank you. Sorry.
